### ISSUE TITLE
Loading of the opf-spec example fails

### ISSUE THREAD

**Issue by abey79** [Pix4D/pyopf#3]
I tried loading the opf-spec example but it failed with the following error:

```python
>>> from pyopf.resolve import resolve
>>> p =resolve(load("examples/project.json"))
Traceback (most recent call last):
  File "/Users/hhip/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.9011.38/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Users/hhip/src/opf-spec/venv/lib/python3.11/site-packages/pyopf/resolve/resolver.py", line 96, in resolve
    obj = io.load(item.resources[0].uri, project.base_uri)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hhip/src/opf-spec/venv/lib/python3.11/site-packages/pyopf/io/loaders.py", line 145, in load
    return loader(*params)
           ^^^^^^^^^^^^^^^
  File "/Users/hhip/src/opf-spec/venv/lib/python3.11/site-packages/pyopf/io/loaders.py", line 35, in _load_from_json
    with open(str(uri)) as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hhip/src/opf-spec/examples/cameras.json'
```

It looks like `opf-spec/examples/project.json` has many mis-formatted links to resource files (`-` vs `_`)—I'm not sure if this is intensional. Are there other example projects available for testing?

**Comment by krahenbuhl** [comment]
Ooops, thanks for noticing! A fix is incoming

**Comment by krahenbuhl** [comment]
Thanks @abey79 
The faulty example should now be fixed in the main branch of https://github.com/Pix4D/opf-spec
We will provide a few demo OPF projects soon, I will update this ticket then

**Comment by abey79** [comment]
Great thanks!

**Comment by krahenbuhl** [comment]
Hi @abey79 -

we have now added some example OPF dataset under: 
https://support.pix4d.com/hc/en-us/articles/360000235126-Example-projects-real-photogrammetry-data

for example https://s3.amazonaws.com/mics.pix4d.com/example_datasets/olympic_flame.zip

**Comment by abey79** [comment]
BTW, we have now published a Rerun example using pyopf: https://github.com/rerun-io/rerun/tree/main/examples/python/open_photogrammetry_format

The visual even made it to our recent release 0.8 announcement: https://twitter.com/rerundotio/status/1684668023959924736

Thanks again for the lib and the dataset 👍🏻
